# Generated by Django 5.0.2 on 2024-04-28 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cliente_contraseña_clienteproducto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 714522)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 715025)),
        ),
        migrations.AlterField(
            model_name='clienteproducto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 714522)),
        ),
        migrations.AlterField(
            model_name='clienteproducto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 715025)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 714522)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 715025)),
        ),
        migrations.AlterField(
            model_name='tipotransaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 714522)),
        ),
        migrations.AlterField(
            model_name='tipotransaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 715025)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 714522)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 1, 30, 56, 715025)),
        ),
    ]
